st.markdown(
    """
    <style>
        body {
            background-image: url('https://r.resimlink.com/USyYKmk.png');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            font-family: 'Roboto', sans-serif;
            color: #ffffff; /* Beyaz metin */
        }
       .stApp {
    background-color: rgba(0, 0, 128, 0); /* Tamamen şeffaf arka plan */
}
